<?php

include("action.php");



$title = "Admin to login";

if (isset($_GET['action'])) {

    $action = htmlspecialchars($_GET['action']);
} else {

    $action = "";
}



$message = "";

$session_name = "";

if (isset($_GET['msg'])) {

    $msg = $_GET['msg'];

    if ($msg == 'error')

        $message = "<div class='alert alert-danger alert-dismissible fade show' role='alert'>Wrong User Id or Password <button data-bs-dismiss='alert' class='btn-close' type='button'></button></div>";

    if ($msg == 'blank')

        $message = "<div class='alert alert-info alert-dismissible fade show' role='alert'><button data-bs-dismiss='alert' class='btn-close' type='button'></button>User Id & Password Should not blank</div>";

    if ($msg == 'invalid')

        $message = "<div class='alert alert-danger alert-dismissible fade show' role='alert'><button data-bs-dismiss='alert' class='btn-close' type='button'></button>Invalid User login</div>";

    if ($msg == 'logout')

        $message = "<div class='alert alert-success alert-dismissible fade show' role='alert'><button data-bs-dismiss='alert' class='btn-close' type='button'></button>Successfully Logged Out !!</div>";
}

$expired_date = $obj->getvalfield("software_expired", "expired_date", "1=1 order by soft_exp_id desc");

$expired = $obj->software_expire();

?>

<!DOCTYPE html>

<html lang="en">



<head>

    <meta charset="UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><?php echo $title; ?></title>

    <meta name="description" content="This is admin panel">

    <meta name="author" content="Om Prakash Kashyap">

    <link rel="stylesheet" href="admin/assets/font/bootstrap-icons.css">

    <link rel="stylesheet" href="admin/assets/css/bootstrap.min.css">

    <link rel="stylesheet" href="admin/assets/css/style.css">

    <style>
        /* Background styles */

        body {
            /* background-color: #364571; */
            background-image: url(bg.jpg);
            background-repeat: no-repeat;
            background-size: cover;
        }

        /* Glassmorphism card effect */

        .card {
            backdrop-filter: blur(16px) saturate(180%);
            -webkit-backdrop-filter: blur(16px) saturate(180%);
            background-color: #03a3bf87;
            border-radius: 12px;
            border: 1px solid rgba(209, 213, 219, 0.3);
            margin-top: 30%;
            display: none;
        }

        /* Generated by https://generator.ui.glass/ */
    </style>

</head>



<body>

    <div class="container">

        <div class="col-md-4 offset-md-4">



            <form action="checklogin.php" method="post" class="card card-body shadow">

                <!--  <center>

                    <img src="logo.jpeg" alt="" style="width: 332px; height: 86px; border-radius: 10px;">

                   

                </center> -->





                <?php if ($expired == 1) {

                    echo $message; ?>


                    <img src="logo.png" alt="" class="mb-2 w-100 rounded-2">
                    <h1 class="text-white">LOGIN</h1>

                    <p class="text-light">Login to access your account.</p>

                    <div class="form-floating mb-3">

                        <input type="text" class="form-control" id="admin_name" name="admin_name" placeholder="User Name" autofocus>

                        <label for="admin_name">User Name</label>

                    </div>

                    <div class="form-floating">

                        <input type="password" class="form-control" id="admin_pwd" name="admin_pwd" placeholder="Password">

                        <label for="admin_pwd">Password</label>

                    </div>

                    <div class="d-grid gap-2 mt-3">

                        <button class="btn btn-outline-light" onclick="return checkinputmaster('admin_name,admin_pwd')" type="submit" name="login">Login</button>

                    </div>

                    <div class="alert alert-primary d-flex align-items-center mt-3" role="alert">

                        <i class="bi bi-info-circle-fill"></i> Software will be expire :

                        <?php echo $obj->dateformatindia($expired_date); ?></span>

                    </div>

                <?php } else { ?>

                    <div id="login-wrapper" class="shadow">

                        <div style="text-align: center;">

                            <h4 style="color: red;">Hosting Expired</h4>

                            <h3 style="color: white;">Kindly contact to administrator for renewal: +91-9770131555</h3>

                        </div>

                    </div>

                <?php } ?>

            </form>

        </div>

    </div>



</body>



<!-- script tag -->

<script src="admin/assets/js/jquery-3.6.0.min.js"></script>

<script src="admin/assets/js/bootstrap.bundle.min.js"></script>

<script src="admin/assets/js/commonfun.js"></script>

<script>
    $(document).ready(function() {

        $('.card').fadeIn(2000);

        $('#admin_name').focus();



    });
</script>

<!-- script tag -->



</html>